### ISSUE TITLE
Implement a Group Signature API

### ISSUE THREAD

**Issue by rheitjoh** [cryptimeleon/craco#15]
# Problem and Requirements

The Craco library currently does not contain any interfaces for group signatures. Therefore, it would be good to add interfaces that allow for any kind of group signatures. Problematic is that there are group signatures with different capabilities and algorithms which makes defining a common interface difficult. Our goal is to offer interfaces that allow for all kinds of group signatures to be implemented.

[Libgroupsig](https://eprint.iacr.org/2015/1146.pdf) have already addressed this issue and have defined and implemented a common interface for group signatures. It would therefore be interesting to see if we can use their results in designing our own interfaces.

Libgroupsig code is hosted [here](https://github.com/IBM/libgroupsig).

**Comment by JanBobolz** [comment]
Are we also planning to implement a conrete group signature construction? If so, why? @feidens

**Comment by feidens** [comment]
I think a group signature API is a good feature to have, because it matches our vision for giving support for high level constructions and most of the other libraries don't have support for it. 
Other reasons for a group signature API and scheme:
* This is something that students can easily use in a thesis
* A group signature is (1) a bit more complicated then the building blocks that we already have and more importantly it is (2) easier to follow than our other higher level implementations, e.g. credential system, incentive system. (1) speaks to that it is a good example to show in an extended documentation or a separate getting starting section. (2) speaks to that it is easier to understand and at once see more of our API in use (also supports (1)).

**Comment by rheitjoh** [comment]
Just to give a status update:

What I have done so far is
- Implement the interface as in the libgroupsig paper except that the group public key is handled like a public parameter instead of being passed to every method. This allows the scheme instance to restore representations. I also removed the trapdoor parameter/result from the reveal method since that is all handled by the revocation list.
- Implement a tester class that automatically collects parameters (if they exist) and tests basic functionality.
- Almost finish implementing a [traceable group signature scheme](https://link.springer.com/chapter/10.1007/11908739_7) from Choi et al. Just lacking the stuff that needs a proof of knowledge since the protocols library is not yet ready for that.

To be done:
- Finish the scheme implementation
- Add some missing methods to the group signature interface such as `mapToPlaintext`. The interface does not extend `SignatureScheme` since the verify method signatures don't match (group signature has no verification key).

For the Choi et al. scheme I made one change to how trace works to match our interface better:
- The trace function as described in libgroupsig works by going over the the revocation list and checking whether the signature was created by any of the users in there. The Choi et al. scheme has this defined a bit differently: The trace method is given just a single reveal trapdoor and checks whether the given signature was created by the user whom that trapdoor belongs to. I would be supporting the version from libgroupsig. That also matches the capabilities of verifier-local group signatures better.

**Comment by JanBobolz** [comment]
> The interface does not extend SignatureScheme since the verify method signatures don't match (group signature has no verification key).

I would disagree. The idea of these interfaces was that every `SignatureScheme` (including any special ones, e.g., group signatures) has some sort of "verification key". In this case, one may think of (part of) the pp as the verification key.

More concretely, I think I would embed group information into the implementation of the `GroupSignature` interface ('I'm setting up this scheme for this BilinearGroup") and then define some sort of keygen algorithm that sets up all the public group elements - those would comprise the verification key.

This is mostly a "consistency" complaint, I'm honestly not sure that it's really advantageous to have this hiearchy `SignatureScheme`-descendants in the interface definition. But it's the way this is currently set up, so I'd vote for keeping this structure for now.

**Comment by rheitjoh** [comment]
A problem with this approach is that the `sign()` method then only takes in a plaintext and a signing key. The signing key can of course just correspond to the member key of the group member creating the signature. However, the group signature algorithm also needs the group public key (i.e. the verification key) as an argument. So the `SignatureScheme.sign()` method would basically be not functional.

This implies we would either have to make a weird composite `SigningKey` class that merges the group public key and the member key, or store the public group elements both in the public parameters as well as in a separate group public key.
Both seem like very obscure design decisions.

Aside from that it also increases verbosity to pass along the group public key to basically every method in the group signature scheme instead of just storing it as a public parameter. Its just a minor annoyance, but still seems unnecessary.
Storing the public group elements in both places would fix this.

Another option would be to implement `SignatureScheme`, but keep the public group elements in the public parameters and instead just implement the `SignatureScheme`'s verify method as a default method in `GroupSignatureScheme`. It would then just call the two-argument verify method, i.e. we just ignore the verification key argument. This is what I had initially before throwing out `SignatureScheme` support.

On a higher level, what is the purpose of even implementing `SignatureScheme`? As I understand it, the purpose of the scheme interfaces in our library is to enforce a shared interface between schemes of the same type. One could argue, that a group signature is different enough from a regular signature scheme to warrant a completely new interface. You are not going to take your regular signature scheme and suddenly slot in a group signature scheme, after all.

**Comment by JanBobolz** [comment]
> Another option would be to implement SignatureScheme, but keep the public group elements in the public parameters and instead just implement the SignatureScheme's verify method as a default method in GroupSignatureScheme. It would then just call the two-argument verify method, i.e. we just ignore the verification key argument.  

I guess that's less clunky to implement this way, true. 

> You are not going to take your regular signature scheme and suddenly slot in a group signature scheme, after all.

In a way, you do. Let's say we implement an email client with email signatures. We can easily imagine using email with standard signatures or with group signatures. The only difference is how/where you'd get your signing and verification keys. But signing an email is the same process (use signing key and message, create signature) and verifying a signature is the same (take signature and verification key [either the specific user's or a group's key] and call verify).

So ideally, you'd set up the scheme once (e.g., some TA would generate a group) and then be able to generate multiple group keys for this scheme (roughly: every group can generate their own group public key and communicate this to identify messages from this group).

I'm not married to this idea, especially since implementing email clients (or any real-world thing) is not the focus of this library. But I think on a higher level, there is some elegance in this idea. 
I don't know. Maybe @feidens has some input w.r.t. the paper we're writing? Is interface unity a selling point?

**Comment by feidens** [comment]
As I see it there are good arguments for all of the solutions. The sell includes some story about easy plug-and-play and that if you think about signatures then you just have to look at the signature interface.

Another thought is that our `SignatureScheme` interface is too limited if it does not encompass public parameters. Maybe we should take a look at this and apply lessons learned from the predicate encryption part.

**Comment by rheitjoh** [comment]
Note: The group signature stuff has been moved to its own [repository](https://github.com/cryptimeleon/groupsig).
