### ISSUE TITLE
Fix RingElementPlainText.getUniqueByteRepresentation() producing arrays of incorrect length

### ISSUE THREAD

**Issue by Colamaleon** [cryptimeleon/craco#98]
[**This issue can be recreated using the following [test class](https://gist.github.com/Colamaleon/1f450677cf782c2494864864064e3d14)**]

Using the function `org.cryptimeleon.math.structures.rings.zn.Zn.injectiveValueOf(byte[] bytes)` after generating a byte array using `org.cryptimeleon.craco.common.plaintexts.RingElementPlainText.getUniqueByteRepresentation()` produces the following error:

`Too many bytes to map injectively to Zn (allowed are byte arrays of length 15)`
Full stack trace [`here`](https://gist.github.com/Colamaleon/342fe0581d8ac0eec43db8f6bb6f04eb)

The byte array generated too long regardless of the security parameter used
(64 -> 10 elements (7 expected), 128 -> 17 elements (15 expected), 256 -> 34 elements (31 expected))

This results in the function `mapToPlainText(byte[] bytes)` not working when implemented by Commitment Schemes that use ZnElements as plain texts, such as the existing implementation of Pedersen Commitments

**Comment by JanBobolz** [comment]
Hey, thanks for the report and the very clear error description!

I've just looked into it and things turn out to be somewhat complicated in this case. I think `injectiveValueOf` in `Zn` can handle fewer bytes as [a feature](https://github.com/cryptimeleon/math/pull/128), since we don't want two byte arrays with different numbers of leading zeros to be mapped to the same value (e.g., [0, 1] and [0, 0, 1] would intuitively be mapped to the same `ZnElement`, and that doesn't really scream "injective"). 
So we can essentially choose whether we want `injectiveValueOf(getUniqueByteRepresentation())` to work (which is what you would have expected) or whether we want the `injectiveValueOf` mapping to still be injective when fed with different-length array inputs. I'm not 100% sure what the right choice is here (since generally, the contract of `injectiveValueOf` is to be injective *on inputs of the same lengths*, we were just being careful).

Can I ask what your use-case is? 

As a workaround, I suggest using `Zn.valueOf` instead of `Zn.injectiveValueOf`, which should probably work for your use-case.

**Comment by Colamaleon** [comment]
Thank you for the thorough response. 
The issue originally arose as I was trying to implement the method `mapToPlainText` as required by the `CommitmentScheme` interface. More specifically, I'm trying to implement the commitment scheme TCgamma seen in [this](https://eprint.iacr.org/2015/076.pdf) paper, p.10.

As I am rather new to this, I looked at the already existing implementation of Pedersen Commitments for guidance, but couldn't resolve the issue, as said implementation also uses `injectiveValueOf ` with bytes generated from ring elements:

```java    
public MessageBlock mapToPlainText(byte[] bytes) throws IllegalArgumentException {
        RingElementPlainText zero = new RingElementPlainText(group.getZn().getZeroElement());
        return new MessageBlock(
                Vector.of(new RingElementPlainText(group.getZn().injectiveValueOf(bytes)))
                        .pad(zero, h.length())
        );
    }
```

It looks like your workaround should fix my problem (going by the results of replacing the method in the minimal test setup) -- though in this case the existing implementation of Pedersen Commitments would need this workaround as well, as it currently runs into the same issue (and does not appear to have unit test coverage for this) -- unless I'm overlooking something?

**Comment by JanBobolz** [comment]
You should imagine `bytes` being the output of a hash function. The idea of `mapToPlainText` is that we can implement "hash-then-commit" (like "hash-then-sign") generically, by calling (roughly): `commit(mapToPlainText(hash(x)))`. 

So a "realistic" test case for `mapToPlainText` would be to generate a bunch of bytes as a hash of something. I don't (right now) see a case for `commit(mapToPlainText(pt.getUniqueByteRepresentation()))`, as instead you'd just call `commit(pt)`. 

Does that make sense?

**Comment by Colamaleon** [comment]
I think so. However, the `CommitmentSchemeTester` as it currently lives on the develop branch, does exactly that, hence my confusion:
(From: [CommitmentSchemeTester.java](https://github.com/cryptimeleon/craco/blob/develop/src/test/java/org/cryptimeleon/craco/commitment/CommitmentSchemeTester.java#L61))
```java
    public static void testCommitmentSchemeMapToPlaintext(CommitmentScheme commitmentScheme, PlainText message) {
        CommitmentPair commitmentPair =
                commitmentScheme.commit(commitmentScheme.mapToPlainText(message.getUniqueByteRepresentation()));
        assertTrue(commitmentScheme.verify(commitmentPair.getCommitment(),
                commitmentPair.getOpenValue(), commitmentScheme.mapToPlainText(message.getUniqueByteRepresentation())));
    }
```

**Comment by JanBobolz** [comment]
Ah. Confusion definitely understandable. That is a weird test case. 
@feidens pledged to change the test case.

**Comment by feidens** [comment]
@Colamaleon you can update your fork to https://github.com/cryptimeleon/craco/commit/489448105453940d686f5fa159832d35d74af19f for your work.

**Comment by feidens** [comment]
Thanks for the hint and the good description.
